#name: 'rttp'
#
#stage1_ckpt: None
#restore_ckpt: None
#lr: 0.0002
#wdecay: 1e-5
batch_size: 1
#num_steps: 100000
#loss_scale: 100
#use_wandb: True
#use_lpips: True

dataset:
  downscale_factor: 8
  data_root: '/playpen-ssd2/mikewang/rttp-data'
  source_cam_names: [['000228212212', "middle"],
                     ['000655594512', "right"],
                     ['000665414412', "up"],
                     ['000738314412', "left"]]
  gt_cam_names: [['000597713512', "gt_left"],
                 ['000907513512', "gt_right"]]
  train_trial_names: ["setup_1210_wsz_1/trial_2",
                      "setup_1210_wsz_1/trial_4",
                      "setup_1210_wsz_1/trial_6",
                      "setup_1210_wsz_1/trial_8",
                      "setup_1210_wsz_1/trial_9",
                      "setup_1210_wsz_2/trial_1",
                      "setup_1210_wsz_2/trial_2",
                      "setup_1210_wsz_2/trial_3",
                      "setup_1210_wsz_2/trial_4",
                      "setup_1210_wsz_2/trial_5",
                      "setup_1210_wsz_2/trial_6",
                      "setup_1210_wsz_2/trial_7",
                      "setup_1210_wsz_2/trial_8",
                      "setup_1210_wsz_2/trial_9",
                      "setup_1210_wsz_2/trial_10",
                      "setup_1212_wsz_1/trial_4",
                      "setup_1212_wsz_1/trial_5",
                      "setup_1212_wsz_1/trial_6",
                      "setup_1212_wsz_1/trial_7",
                      "setup_1212_wsz_1/trial_8",
                      "setup_1212_wsz_1/trial_9",
                      "setup_1212_wsz_1/trial_10",
                      "setup_0218_wsz_1/trial_1",
                      "setup_0218_wsz_1/trial_2",
                      "setup_0218_wsz_1/trial_3",
                      "setup_0218_wsz_1/trial_4",
                      "setup_0218_wsz_2/trial_2",]
  val_trial_names: ["setup_1210_wsz_1/trial_5",
                    "setup_1210_wsz_1/trial_7",
                    "setup_0218_wsz_3/trial_intro",]
  test_trial_names: ["setup_0302_wsz_1/trial_test9",]
#                     "setup_0218_wsz_3/trial_intro",
#                     "setup_0302_wsz_1/trial_test10",
#                     "setup_0302_wsz_1/trial_test11",
#                     "setup_0302_wsz_1/trial_test12",
#                     "setup_0302_wsz_1/trial_test13",
#                     "setup_0302_wsz_1/trial_test14"]

#raft:
#  mixed_precision: True
#  train_iters: 3
#  val_iters: 3
#  encoder_dims: [32, 48, 96]
#  hidden_dims: [96, 96, 96]
#
#gsnet:
#  encoder_dims: [32, 48, 96]
#  decoder_dims: [48, 64, 96]
#  parm_head_dim: 32
#
#record:
#  loss_freq: 1000
#  eval_freq: 10000